export default{
    HOME:'Home',
    LOGIN:'Profile',
    APPTOUR:'AppTour',
    MYTABS:'MyTabs',
    RECENT:'Recent',
    EXAMS:'Exams',
    PROFILE:'Profile',
    CONTACT:'Contact',
    EXAM_CORNER:'Exam Corner',
    SUBSCRIPTION:'Subscription',
    ANALYTICS:'Analytics',
    DOWNLOADS:'Downloads',
    NOTIFICATIONS:'Notifications',
    REFERALS:'Referals',
    SHARE_APP:'Share App',
    LOGOUT:'Log Out',
    MYDRAWER:'MyDrawer',
    SUBJECT_SCREEN:'Subject Screen',
    HOME_STACK:'Home_Stack',
    CHAPTER_TAB:'Chapter Tab',
    VIDEOS:'Vidoes',
    CHAPTER_TEST:'Chapter Test',
    QN_BANK:'Qn Bank',
    RESOURCES:'Resources'

}